import { useState } from 'react';
import { faqItems, workshopDetails } from './workshop';
import ziyaoPhoto from '../../portfolio/src/ziyao_photo.jpeg';

const facts = [
  ['Workshop', workshopDetails.title], ['Who it is for', workshopDetails.audience], ['Experience', workshopDetails.experience],
  ['Length', workshopDetails.duration], ['Format', workshopDetails.format], ['Cost', workshopDetails.cost],
  ['Software', workshopDetails.software], ['Location', workshopDetails.location], ['Date', workshopDetails.date], ['Time', workshopDetails.time], ['Capacity', workshopDetails.capacity],
];

const registrationCopy = {
  'coming-soon': { label: 'Registration opening soon', note: 'Pilot workshop details are being finalized. Join the interest list to hear first.', event: 'learn_interest_click' },
  open: { label: 'Register for the Workshop', note: 'Registration is open while seats remain.', event: 'learn_registration_click' },
  full: { label: 'Workshop full', note: 'This pilot is full. Join the waitlist to hear about the next session.', event: 'learn_interest_click' },
  waitlist: { label: 'Join the waitlist', note: 'The workshop is currently full; new openings will be shared by email.', event: 'learn_interest_click' },
};

function track(event: string) { window.gtag?.('event', event); }

function Logo() { return <svg viewBox="120 120 760 760" aria-hidden="true" className="logo-mark"><polygon fill="none" stroke="currentColor" strokeWidth="29" strokeLinecap="round" strokeLinejoin="round" points="500 123.78 174.18 311.89 174.18 688.11 500 876.22 825.82 688.11 825.82 311.89 500 123.78"/><circle fill="none" stroke="currentColor" strokeWidth="29" cx="500" cy="500" r="162.65"/><circle fill="currentColor" cx="500" cy="500" r="105"/></svg>; }

function Header() {
  const [open, setOpen] = useState(false);
  const links = [['Workshop', '#workshop'], ['The project', '#create'], ['Prepare', '#prepare'], ['FAQ', '#faq'], ['Register', '#registration']];
  return <header className="site-header"><a className="brand-lockup" href="#top" aria-label="Summer CAD Workshop home"><Logo/><span>KINETIC LOGIC LABS<small>SUMMER CAD WORKSHOP</small></span></a><nav className="desktop-nav" aria-label="Workshop navigation">{links.map(([label, href]) => <a href={href} key={label}>{label}</a>)}</nav><div className={`mobile-nav ${open ? 'is-open' : ''}`}><button type="button" aria-expanded={open} aria-controls="mobile-navigation" onClick={() => setOpen(!open)}><span aria-hidden="true">{open ? '×' : '☰'}</span><span className="visually-hidden">{open ? 'Close menu' : 'Open menu'}</span></button><nav id="mobile-navigation" aria-label="Workshop navigation">{links.map(([label, href]) => <a key={label} href={href} onClick={() => setOpen(false)}>{label}</a>)}</nav></div><span className="issue">SUMMER 2026</span></header>;
}

function CadGraphic() { return <div className="cad-graphic" aria-hidden="true"><svg viewBox="0 0 600 500" role="presentation"><defs><pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M 32 0 L 0 0 0 32" fill="none" stroke="currentColor" strokeOpacity=".18" strokeWidth="1"/></pattern></defs><rect width="600" height="500" fill="url(#grid)"/><g className="cad-solid"><path d="M174 285 302 212 431 285 302 359Z"/><path d="M174 285v-116l128-73v116Z"/><path d="M302 212V96l129 73v116Z"/><path d="M302 359v-147"/><path d="M174 169 302 242l129-73"/></g><g className="dimension"><path d="M174 401h257M174 386v30m257-30v30M151 164l-38 22m48-4-38 22"/><text x="270" y="437">84.0 mm</text><text x="51" y="188">SKETCH</text></g><g className="axis"><path d="M485 385h55m-28 27v-54"/><text x="546" y="389">X</text><text x="488" y="438">Y</text></g></svg><span className="cad-caption">MODEL STUDY / 01</span></div>; }

function FAQ() { const [open, setOpen] = useState<number | null>(0); return <section className="faq section" id="faq"><div className="section-intro"><span className="coral-label">COMMON QUESTIONS</span><h2>Clear before you arrive.</h2></div><div className="accordion">{faqItems.map(([question, answer], index) => <div className="faq-item" key={question}><h3><button type="button" aria-expanded={open === index} aria-controls={`answer-${index}`} onClick={() => setOpen(open === index ? null : index)}><span>{question}</span><b aria-hidden="true">{open === index ? '−' : '+'}</b></button></h3><div id={`answer-${index}`} role="region" aria-label={question} hidden={open !== index}><p>{answer}</p></div></div>)}</div></section>; }

export default function App() {
  const register = registrationCopy[workshopDetails.registrationStatus];
  return <div className="site-shell"><a className="skip-link" href="#main">Skip to content</a><Header/><main id="main"><section className="learn-hero" id="top"><div className="measure hero-inner"><div><span className="coral-label">KINETIC LOGIC LABS · LEARN</span><h1>Design<br/>something real.</h1><p>A beginner-friendly summer workshop where students learn the foundations of CAD by creating their own 3D model in Fusion.</p><div className="hero-actions"><a className="button button-primary" href={workshopDetails.registrationUrl} onClick={() => track(register.event)}>{register.label} <span>→</span></a><a className="button button-secondary" href="#create">See what you’ll learn</a></div></div><CadGraphic/></div></section>
  <section className="facts section" id="workshop" aria-labelledby="facts-title"><div className="section-intro"><span className="coral-label">WORKSHOP / 001</span><h2 id="facts-title">A first look at how things get made.</h2><p>One focused, hands-on session for curious students ready to turn an idea into a precise digital object.</p></div><dl>{facts.map(([term, definition]) => <div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl></section>
  <section className="creation section" id="create"><div className="section-intro"><span className="coral-label">THE PROJECT</span><h2>Create your first 3D model.</h2><p>Students will follow a guided design process to create and personalize a small 3D-printable object. They will leave with a completed digital design of their own.</p></div><ol className="process"><li><span>01</span><strong>Start with a sketch</strong><small>Map an idea in two dimensions.</small></li><li><span>02</span><strong>Add dimensions<br/>and constraints</strong><small>Make geometry intentional and precise.</small></li><li><span>03</span><strong>Build a 3D form</strong><small>Turn the sketch into a solid model.</small></li><li><span>04</span><strong>Personalize<br/>the design</strong><small>Add details that make it yours.</small></li><li><span>05</span><strong>Save and export</strong><small>Leave with a finished digital model.</small></li></ol></section>
  <section className="learning section"><div className="learning-grid"><div className="section-intro"><span className="coral-label">WHAT STUDENTS LEARN</span><h2>Tools matter. Thinking matters more.</h2><p>This workshop focuses on the thinking behind CAD: defining geometry, controlling dimensions, testing ideas, and improving a design.</p></div><ul className="outcomes"><li>Navigating a professional CAD workspace</li><li>Creating and editing sketches</li><li>Using dimensions to control geometry</li><li>Turning sketches into 3D forms</li><li>Adding fillets, holes, text, and details</li><li>Saving, exporting, and revising a model</li></ul></div></section>
  <section className="timeline section"><div className="section-intro"><span className="coral-label">90-MINUTE SESSION</span><h2>A guided, achievable build.</h2></div><div className="timeline-list">{[['10 min','Welcome and demonstration'],['15 min','Fusion basics'],['40 min','Guided model build'],['15 min','Independent customization'],['10 min','Export, showcase, and closing']].map(([time, name], i) => <div key={name}><span>{String(i + 1).padStart(2, '0')}</span><strong>{name}</strong><small>{time}</small></div>)}</div></section>
  <section className="prep section" id="prepare"><div className="section-intro"><span className="coral-label">STUDENT PREPARATION</span><h2>Bring a ready-to-design setup.</h2><p>Detailed setup instructions will be sent after registration.</p></div><div className="prep-content"><ul><li>A compatible laptop and charger</li><li>A mouse, if available</li><li>An Autodesk account</li><li>Autodesk Fusion installed and tested before arrival</li></ul><aside><span>SETUP CHECK</span><p>Students should open Fusion and confirm they can create a blank design before attending. This keeps workshop time focused on making.</p><a href={`mailto:${workshopDetails.contactEmail}?subject=CAD%20workshop%20setup%20instructions`} onClick={() => track('learn_setup_click')}>ASK ABOUT SETUP →</a></aside></div></section>
  <section className="instructor section"><div className="instructor-image"><img src={ziyaoPhoto} alt="Ziyao Xu, creator of Kinetic Logic Labs" loading="lazy"/><span>FIG. 01 — ZIYAO XU / WORKSHOP LEAD</span></div><div className="section-intro"><span className="coral-label">ABOUT THE INSTRUCTOR</span><h2>Led by Ziyao Xu.</h2><p>Ziyao is a student designer and the creator of Kinetic Logic Labs. His work focuses on CAD, prototyping, mechanical design, 3D printing, and engineering projects.</p><p>The workshop was created to give younger students a practical and approachable first experience with professional design tools.</p><a className="action-link" href="https://kineticlogiclabs.org/">Explore Kinetic Logic Labs →</a></div></section>
  <section className="parents section"><div className="section-intro"><span className="coral-label">FOR PARENTS &amp; GUARDIANS</span><h2>Built for beginners, organized for families.</h2></div><div><p>The workshop is designed for beginners and requires registration because space is limited. A parent or guardian must provide contact information, and students should arrive with the required software already installed.</p><p>Final supervision, arrival, pickup, and attendance details will be provided before the event.</p><blockquote>This workshop is independently organized by Kinetic Logic Labs and is not sponsored or endorsed by the King County Library System.</blockquote></div></section>
  <FAQ/>
  <section className="registration" id="registration"><div className="measure"><span className="coral-label">SUMMER CAD WORKSHOP</span><h2>Ready to start designing?</h2><p>Space for the pilot workshop is intentionally limited so each student can receive individual help.</p><a className="button button-primary" href={workshopDetails.registrationUrl} onClick={() => track(register.event)}>{register.label} <span>→</span></a><small>{register.note}</small><a className="contact-link" href={`mailto:${workshopDetails.contactEmail}?subject=Summer%20CAD%20Workshop`} onClick={() => track('learn_contact_click')}>Questions? Contact Kinetic Logic Labs</a></div></section></main><footer className="site-footer"><div className="footer-inner"><div><a className="brand-lockup" href="#top"><Logo/><span>KINETIC LOGIC LABS<small>SUMMER CAD WORKSHOP</small></span></a><p>A student-led, beginner-friendly introduction to CAD and digital fabrication.</p></div><nav aria-label="Workshop navigation"><span className="section-label">WORKSHOP</span><a href="#workshop">Workshop details</a><a href="#create">The project</a><a href="#prepare">Student preparation</a><a href="#faq">Questions</a><a href="#registration">Registration</a></nav><div className="footer-note"><span>© 2026 KINETIC LOGIC LABS</span><small>SUMMER CAD WORKSHOP</small></div></div></footer></div>;
}

declare global { interface Window { gtag?: (...args: unknown[]) => void } }
